name: Check
on:
  pull_request: ~
  push:
    branches:
      - main

permissions: read-all

jobs:
  ci:
    name: CI Workflows
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Install asdf
        uses: asdf-vm/actions/setup@4f8f7939dd917fc656bb7c3575969a5988c28364 # v3.0.0
      - name: Add plugins
        run: |
          asdf plugin add actionlint https://github.com/crazy-matt/asdf-actionlint.git
          asdf plugin add shellcheck https://github.com/luizm/asdf-shellcheck.git
          asdf plugin add shfmt https://github.com/luizm/asdf-shfmt
          asdf plugin add yamllint https://github.com/ericcornelissen/asdf-yamllint
      - name: Install tooling
        uses: asdf-vm/actions/install@4f8f7939dd917fc656bb7c3575969a5988c28364 # v3.0.0
      - name: Lint
        run: make lint-ci
  secrets:
    name: Secrets
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0
      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@cb7149a9b57195b609c63e8518d2c6056677d2d0 # v2.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ENABLE_COMMENTS: false
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: false
          GITLEAKS_ENABLE_SUMMARY: false
  shell:
    name: Shell scripts
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Install asdf
        uses: asdf-vm/actions/setup@4f8f7939dd917fc656bb7c3575969a5988c28364 # v3.0.0
      - name: Add plugins
        run: |
          asdf plugin add actionlint https://github.com/crazy-matt/asdf-actionlint.git
          asdf plugin add shellcheck https://github.com/luizm/asdf-shellcheck.git
          asdf plugin add shfmt https://github.com/luizm/asdf-shfmt
          asdf plugin add yamllint https://github.com/ericcornelissen/asdf-yamllint
      - name: Install tooling
        uses: asdf-vm/actions/install@4f8f7939dd917fc656bb7c3575969a5988c28364 # v3.0.0
      - name: Lint
        run: make lint-sh
      - name: Format
        run: make format-check
  types:
    name: Types
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Validate action types
        uses: krzema12/github-actions-typing@e9e977de7a340aa04bd5c19aa14ee69a85528522 # v1.0.3
  yaml:
    name: YAML
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Install asdf
        uses: asdf-vm/actions/setup@4f8f7939dd917fc656bb7c3575969a5988c28364 # v3.0.0
      - name: Add plugins
        run: |
          asdf plugin add actionlint https://github.com/crazy-matt/asdf-actionlint.git
          asdf plugin add shellcheck https://github.com/luizm/asdf-shellcheck.git
          asdf plugin add shfmt https://github.com/luizm/asdf-shfmt
          asdf plugin add yamllint https://github.com/ericcornelissen/asdf-yamllint
      - name: Install tooling
        uses: asdf-vm/actions/install@4f8f7939dd917fc656bb7c3575969a5988c28364 # v3.0.0
      - name: Lint
        run: make lint-yml
