name: Check
on:
  pull_request: ~
  push:
    branches:
      - main

permissions: read-all

jobs:
  ci:
    name: CI Workflows
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Install asdf
        uses: asdf-vm/actions/setup@75bab86b342b8aa14f3b547296607599522cbe90 # v2.1.0
      - name: Add plugins
        run: |
          asdf plugin add actionlint https://github.com/crazy-matt/asdf-actionlint.git
          asdf plugin add shellcheck https://github.com/luizm/asdf-shellcheck.git
          asdf plugin add shfmt https://github.com/luizm/asdf-shfmt
          asdf plugin add yamllint https://github.com/ericcornelissen/asdf-yamllint
      - name: Install tooling
        uses: asdf-vm/actions/install@75bab86b342b8aa14f3b547296607599522cbe90 # v2.1.0
      - name: Lint
        run: make lint-ci
  markdown:
    name: MarkDown
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Install markdownlint-cli
        run: npm install --global markdownlint-cli
      - name: Lint
        run: make lint-md
  secrets:
    name: Secrets
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 0
      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@e7168103501562d92f3f52e2c69c253cff74438d # v2.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ENABLE_COMMENTS: false
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: false
          GITLEAKS_ENABLE_SUMMARY: false
  shell:
    name: Shell scripts
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Install asdf
        uses: asdf-vm/actions/setup@75bab86b342b8aa14f3b547296607599522cbe90 # v2.1.0
      - name: Add plugins
        run: |
          asdf plugin add actionlint https://github.com/crazy-matt/asdf-actionlint.git
          asdf plugin add shellcheck https://github.com/luizm/asdf-shellcheck.git
          asdf plugin add shfmt https://github.com/luizm/asdf-shfmt
          asdf plugin add yamllint https://github.com/ericcornelissen/asdf-yamllint
      - name: Install tooling
        uses: asdf-vm/actions/install@75bab86b342b8aa14f3b547296607599522cbe90 # v2.1.0
      - name: Lint
        run: make lint-sh
      - name: Format
        run: make format-check
  types:
    name: Types
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Validate action types
        uses: krzema12/github-actions-typing@5bf880e54403b345c182e6fdedc321781f2d7550 # v1.0.0
  yaml:
    name: YAML
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Install asdf
        uses: asdf-vm/actions/setup@75bab86b342b8aa14f3b547296607599522cbe90 # v2.1.0
      - name: Add plugins
        run: |
          asdf plugin add actionlint https://github.com/crazy-matt/asdf-actionlint.git
          asdf plugin add shellcheck https://github.com/luizm/asdf-shellcheck.git
          asdf plugin add shfmt https://github.com/luizm/asdf-shfmt
          asdf plugin add yamllint https://github.com/ericcornelissen/asdf-yamllint
      - name: Install tooling
        uses: asdf-vm/actions/install@75bab86b342b8aa14f3b547296607599522cbe90 # v2.1.0
      - name: Lint
        run: make lint-yml
