name: Publish
on: # yamllint disable-line rule:truthy
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions: read-all

jobs:
  github:
    name: GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # To create a GitHub Release
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          fetch-depth: 0
      - name: Get version
        uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0 # v6.3.3
        id: version
        with:
          result-encoding: string
          script: |
            const ref = context.ref
            const tag = ref.replace(/^refs\/tags\//, "")
            return tag
      - name: Get major version
        uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0 # v6.3.3
        id: major_version
        with:
          result-encoding: string
          script: |
            const tag = "${{ steps.version.outputs.result }}"
            const majorVersion = tag.split(".")[0]
            return majorVersion
      - name: Update major version branch
        run: |
          git push origin HEAD:${{ steps.major_version.outputs.result }} --force
      - name: Create GitHub Release
        uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e # v1.12.0
        with:
          name: Release ${{ steps.version.outputs.result }}
          tag: ${{ steps.version.outputs.result }}
          draft: false
          makeLatest: true
          prerelease: false
