name: Test
on:
  pull_request:
    paths:
      - .github/workflows/test.yml
      - testdata/**
      - test/**
      - bin/*.sh
      - lib/*.sh
      - action.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/test.yml
      - testdata/**
      - test/**
      - bin/*.sh
      - lib/*.sh
      - action.yml

permissions: read-all

jobs:
  unit:
    name: Unit
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Run tests
        run: make test
  e2e:
    name: End-to-end
    runs-on: ubuntu-22.04
    needs:
      - unit
    steps:
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Run action
        id: test
        uses: ./
        with:
          file: testdata/codecov.yml
      - name: Check outputs
        env:
          STATUS_CODE: ${{ steps.test.outputs.status-code }}
        run: |
          if [ "${STATUS_CODE}" != "200" ]; then
            exit 1
          fi
