name: Test
on:
  pull_request:
    paths:
      - .github/workflows/test.yml
      - testdata/codecov.yml
      - action.yml
      - validate.sh
  push:
    branches:
      - main
    paths:
      - .github/workflows/test.yml
      - testdata/codecov.yml
      - action.yml
      - validate.sh

permissions: read-all

jobs:
  e2e:
    name: End-to-end
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1
      - name: Run action
        id: test
        uses: ./
        with:
          file: testdata/codecov.yml
      - name: Check outputs
        run: |
          if [ "${{ steps.test.outputs.status-code }}" != "200" ]; then
            exit 1
          fi
