name: Test
on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - .github/workflows/test.yml
      - testdata/codecov.yml
      - action.yml
      - validate.sh
  push:
    branches:
      - main
    paths:
      - .github/workflows/test.yml
      - testdata/codecov.yml
      - action.yml
      - validate.sh

permissions: read-all

jobs:
  e2e:
    name: End-to-end
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - name: Run action
        id: test
        uses: ./
        with:
          file: testdata/codecov.yml
      - name: Check outputs
        run: |
          if [ "${{ steps.test.outputs.status-code }}" != "200" ]; then
            exit 1
          fi
