name: Test
on:
  pull_request:
    paths:
      - .github/workflows/test.yml
      - testdata/**
      - test/**
      - action.yml
      - validate.sh
  push:
    branches:
      - main
    paths:
      - .github/workflows/test.yml
      - testdata/**
      - test/**
      - action.yml
      - validate.sh

permissions: read-all

jobs:
  unit:
    name: Unit
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Run tests
        if: ${{ !env.ACT }}
        run: make test
  e2e:
    name: End-to-end
    runs-on: ubuntu-22.04
    needs:
      - unit
    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Run action
        id: test
        uses: ./
        with:
          file: testdata/codecov.yml
      - name: Check outputs
        env:
          STATUS_CODE: ${{ steps.test.outputs.status-code }}
        run: |
          if [ "${STATUS_CODE}" != "200" ]; then
            exit 1
          fi
