name: Tooling
on:
  schedule:
    - cron: 0 5 * * *
  workflow_dispatch: ~

permissions: read-all

jobs:
  tooling:
    name: Update tooling
    runs-on: ubuntu-latest
    permissions:
      contents: write # To push a commit
      pull-requests: write # To open a Pull Request
    steps:
      - name: Create token to create Pull Request
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: automation-token
        with:
          app_id: ${{ secrets.AUTOMATION_ID }}
          private_key: ${{ secrets.AUTOMATION_PRIVATE_KEY }}
      - name: Update tooling
        uses: ericcornelissen/tool-versions-update-action/pr@36a2649aecad3f9e1f29e5932dad757e0a719a0f # v0.3.11
        with:
          labels: dependencies
          max: 1
          token: ${{ steps.automation-token.outputs.token }}
