name: Tooling
on:
  schedule:
    - cron: 0 5 * * *
  workflow_dispatch: ~

permissions: read-all

jobs:
  tooling:
    name: Update tooling
    runs-on: ubuntu-latest
    permissions:
      contents: write # To push a commit
      pull-requests: write # To open a Pull Request
    steps:
      - name: Update tooling
        uses: ericcornelissen/tool-versions-update-action/pr@0792d8ab61d762b7bc3cc7b1d2ecd6b6a4887881 # v0.3.4
        with:
          labels: dependencies
          max: 1
